name: release version

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci]')"
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs"
          git-release-bot-name: "GitHub Actions"
          git-release-bot-email: "actions@github.com"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          maven-servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ github.token }}"}]'
